/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as PlusRouteImport } from './routes/plus'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MeRouteImport } from './routes/me'
import { Route as LocalRouteImport } from './routes/local'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlusOfferRouteImport } from './routes/plus.offer'
import { Route as PlusLocalRouteImport } from './routes/plus.local'
import { Route as PlusBusinessRouteImport } from './routes/plus.business'
import { Route as LocalIdRouteImport } from './routes/local.$id'
import { Route as ClaimCodeRouteImport } from './routes/claim.$code'
import { Route as BusinessIdRouteImport } from './routes/business.$id'

const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const PlusRoute = PlusRouteImport.update({
  id: '/plus',
  path: '/plus',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalRoute = LocalRouteImport.update({
  id: '/local',
  path: '/local',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlusOfferRoute = PlusOfferRouteImport.update({
  id: '/offer',
  path: '/offer',
  getParentRoute: () => PlusRoute,
} as any)
const PlusLocalRoute = PlusLocalRouteImport.update({
  id: '/local',
  path: '/local',
  getParentRoute: () => PlusRoute,
} as any)
const PlusBusinessRoute = PlusBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => PlusRoute,
} as any)
const LocalIdRoute = LocalIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LocalRoute,
} as any)
const ClaimCodeRoute = ClaimCodeRouteImport.update({
  id: '/claim/$code',
  path: '/claim/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessIdRoute = BusinessIdRouteImport.update({
  id: '/business/$id',
  path: '/business/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/local': typeof LocalRouteWithChildren
  '/me': typeof MeRoute
  '/notifications': typeof NotificationsRoute
  '/packages': typeof PackagesRoute
  '/plus': typeof PlusRouteWithChildren
  '/saved': typeof SavedRoute
  '/business/$id': typeof BusinessIdRoute
  '/claim/$code': typeof ClaimCodeRoute
  '/local/$id': typeof LocalIdRoute
  '/plus/business': typeof PlusBusinessRoute
  '/plus/local': typeof PlusLocalRoute
  '/plus/offer': typeof PlusOfferRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/local': typeof LocalRouteWithChildren
  '/me': typeof MeRoute
  '/notifications': typeof NotificationsRoute
  '/packages': typeof PackagesRoute
  '/plus': typeof PlusRouteWithChildren
  '/saved': typeof SavedRoute
  '/business/$id': typeof BusinessIdRoute
  '/claim/$code': typeof ClaimCodeRoute
  '/local/$id': typeof LocalIdRoute
  '/plus/business': typeof PlusBusinessRoute
  '/plus/local': typeof PlusLocalRoute
  '/plus/offer': typeof PlusOfferRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/local': typeof LocalRouteWithChildren
  '/me': typeof MeRoute
  '/notifications': typeof NotificationsRoute
  '/packages': typeof PackagesRoute
  '/plus': typeof PlusRouteWithChildren
  '/saved': typeof SavedRoute
  '/business/$id': typeof BusinessIdRoute
  '/claim/$code': typeof ClaimCodeRoute
  '/local/$id': typeof LocalIdRoute
  '/plus/business': typeof PlusBusinessRoute
  '/plus/local': typeof PlusLocalRoute
  '/plus/offer': typeof PlusOfferRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/local'
    | '/me'
    | '/notifications'
    | '/packages'
    | '/plus'
    | '/saved'
    | '/business/$id'
    | '/claim/$code'
    | '/local/$id'
    | '/plus/business'
    | '/plus/local'
    | '/plus/offer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/local'
    | '/me'
    | '/notifications'
    | '/packages'
    | '/plus'
    | '/saved'
    | '/business/$id'
    | '/claim/$code'
    | '/local/$id'
    | '/plus/business'
    | '/plus/local'
    | '/plus/offer'
  id:
    | '__root__'
    | '/'
    | '/local'
    | '/me'
    | '/notifications'
    | '/packages'
    | '/plus'
    | '/saved'
    | '/business/$id'
    | '/claim/$code'
    | '/local/$id'
    | '/plus/business'
    | '/plus/local'
    | '/plus/offer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocalRoute: typeof LocalRouteWithChildren
  MeRoute: typeof MeRoute
  NotificationsRoute: typeof NotificationsRoute
  PackagesRoute: typeof PackagesRoute
  PlusRoute: typeof PlusRouteWithChildren
  SavedRoute: typeof SavedRoute
  BusinessIdRoute: typeof BusinessIdRoute
  ClaimCodeRoute: typeof ClaimCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plus': {
      id: '/plus'
      path: '/plus'
      fullPath: '/plus'
      preLoaderRoute: typeof PlusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local': {
      id: '/local'
      path: '/local'
      fullPath: '/local'
      preLoaderRoute: typeof LocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plus/offer': {
      id: '/plus/offer'
      path: '/offer'
      fullPath: '/plus/offer'
      preLoaderRoute: typeof PlusOfferRouteImport
      parentRoute: typeof PlusRoute
    }
    '/plus/local': {
      id: '/plus/local'
      path: '/local'
      fullPath: '/plus/local'
      preLoaderRoute: typeof PlusLocalRouteImport
      parentRoute: typeof PlusRoute
    }
    '/plus/business': {
      id: '/plus/business'
      path: '/business'
      fullPath: '/plus/business'
      preLoaderRoute: typeof PlusBusinessRouteImport
      parentRoute: typeof PlusRoute
    }
    '/local/$id': {
      id: '/local/$id'
      path: '/$id'
      fullPath: '/local/$id'
      preLoaderRoute: typeof LocalIdRouteImport
      parentRoute: typeof LocalRoute
    }
    '/claim/$code': {
      id: '/claim/$code'
      path: '/claim/$code'
      fullPath: '/claim/$code'
      preLoaderRoute: typeof ClaimCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/$id': {
      id: '/business/$id'
      path: '/business/$id'
      fullPath: '/business/$id'
      preLoaderRoute: typeof BusinessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LocalRouteChildren {
  LocalIdRoute: typeof LocalIdRoute
}

const LocalRouteChildren: LocalRouteChildren = {
  LocalIdRoute: LocalIdRoute,
}

const LocalRouteWithChildren = LocalRoute._addFileChildren(LocalRouteChildren)

interface PlusRouteChildren {
  PlusBusinessRoute: typeof PlusBusinessRoute
  PlusLocalRoute: typeof PlusLocalRoute
  PlusOfferRoute: typeof PlusOfferRoute
}

const PlusRouteChildren: PlusRouteChildren = {
  PlusBusinessRoute: PlusBusinessRoute,
  PlusLocalRoute: PlusLocalRoute,
  PlusOfferRoute: PlusOfferRoute,
}

const PlusRouteWithChildren = PlusRoute._addFileChildren(PlusRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocalRoute: LocalRouteWithChildren,
  MeRoute: MeRoute,
  NotificationsRoute: NotificationsRoute,
  PackagesRoute: PackagesRoute,
  PlusRoute: PlusRouteWithChildren,
  SavedRoute: SavedRoute,
  BusinessIdRoute: BusinessIdRoute,
  ClaimCodeRoute: ClaimCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
